# Header
menu:
  主页: /
  所有文章: /archives
  日志: /categories/日志
  学习笔记: /categories/学习笔记
  项目实战: /categories/项目实战

# SubNav
subnav:
  github: "http://github.com/huahua2"
  weibo: "http://weibo.com/lghua"
#  rss: "#"
#  zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /img/1.ico

#你的头像url
avatar: '/img/author.jpg'
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: lghua
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  蓝海健康云: http://bosjk.com


#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 热衷研究前端的技术的前端er，在这里与你一起阅读、记录、思考、总结、分享…